### PR TITLE
QEMU fix, compile time check suggestion

### PR DESCRIPTION
**Pull request by onsdagens**
This updates the QEMU output to what is expected, and applies the suggestions i made on your PR.

### CODE REVIEW

**Comment by onsdagens** [comment]
strange, i'm looking into it.

**Comment by onsdagens** [comment]
now i see what you were saying about the QEMU output haha, indeed it doesn't match expected behaviour

**Comment by jessebraham** [comment]
> now i see what you were saying about the QEMU output haha, indeed it doesn't match expected behaviour

Yeah sorry I should have been a bit more clear in my original comment, glad you figured it out though 😅

**Review by jessebraham — APPROVED** [review]
Thanks!

**Pull request merged**
